# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('trump', 'TRUMP'), ('hillary', 'HILLARY'), ('elections', 'ELECTIONS'), ('usa', 'USA'), ('india', 'INDIA'), ('android', 'ANDROID'), ('sdlive', 'SDLIVE')], max_length=15)),
            ],
        ),
    ]
